### ISSUE TITLE
SilverStripe 4 support?

### ISSUE THREAD

**Issue by sminnee** [silvershop/silvershop-core#623]
It'd be great to get a SilverStripe 4-compatbile version of this going – we'd like to use it in demo pitches and we're basing all of those on SilverStripe 4 these days.

In my view, it would be better to get a version that operates the same but works in SilverStripe 4, rather than expanding the project with too many other refactoring / new feature ideas, but it would be good to hear other views on that too.

## Tasks

 * [x] Complete https://github.com/silvershop/silverstripe-listsorter/issues/14 (needed for ProductCategory)
 * [x] Complete https://github.com/burnbright/silverstripe-sqlquerylist/issues/6 (needed for ShopPeriodReport)
 * [x] Run updater script
 * [x] Run phpcbf to convert to PSR2 styleguide (if not already)
 * [x] Fix issues reported by `phpcs` 
 * [x] Add namespaces to code
 * [x] Move into PSR-4 compatible filenames / folders, add PSR-4 metadata to composer.json
 * [x] Make "silverstripe-vendormodule"
 * [x] Update all translations locally
 * [x] Push translations to transifex
 * [x] Update documentation
 * [x] Change Icons so that they fit into the SS4 CMS

**Comment by bummzack** [comment]
Yeah I know. I'd *love* to improve the codebase (there's so much to do) and I hope to have some spare time over the holidays.
It's kinda sad… there seem to be quite a lot of people using shop, yet there are barely any contributions. Will start with a 1:1 port for SS4 and go from there.

**Comment by wilr** [comment]
👍 Omnipay 4.0 upgrade was a pre-cursor to shop 4.0 support but that is now started and in progress enough that I've got omnipay + SS4 working in production at the moment. That work probably needs to be finished off first.

I think the best idea as per @bummzack is to start with just a 1:1 to get something to work and go from there. I'm still offline for a couple more weeks but I'll be kicking back into gear for SilverShop next year if anyone hasn't looked into it sooner

**Comment by sminnee** [comment]
@wilr we were gonna maybe start looking at this on our hackday tomorrow.

Is your omnipay work on public repos / put into PRs yet? I see that the master branch on https://github.com/silverstripe/silverstripe-omnipay supports ss4 so I assume that it's it? I see that it still uses omnipay 2. Just noted this though: https://github.com/silverstripe/silverstripe-omnipay/issues/178

We also have these dependencies to upgrade, but I'm not sure how critical they are:
 * https://github.com/silvershop/silverstripe-listsorter/issues/14
 * https://github.com/burnbright/silverstripe-sqlquerylist/issues/6
 * https://github.com/markguinn/silverstripe-email-helpers/issues/25

**Comment by bummzack** [comment]
@sminnee Yeah, the master branch is the SS4 release. Omnipay 3 isn't stable yet (currently an alpha release is out), that's why we still use 2.

**Comment by bummzack** [comment]
I'm not too sure if these additional modules are still required and if they should remain as external modules (apart from the email-helpers, they seem to be only used in the silvershop context anyway). I suggest to try the update without these dependencies first and then decide how critical they are.

**Comment by sminnee** [comment]
I dunno, I think Franco is already on submitting PRs for them — it seemed like an easier place to start than diving into silvershop-core ;-)

**Comment by bummzack** [comment]
Uh, this wasn't meant to be closed, as we're not fully there yet.

**Comment by bummzack** [comment]
Just tagged an alpha release: https://github.com/silvershop/silvershop-core/releases/tag/3.0.0-alpha1

**Comment by wilr** [comment]
Closing this as documentation been merged in 👍
